[tool.poetry]
name = "itsolution-test"
version = "0.1.0"
description = ""
authors = ["xseniaKri <kseniaenta@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
